### ISSUE TITLE
Add "Best Practices" page

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/docs#11]
There are cases where I see multiple people tackling adding in a language's concepts, but they do it in vastly different ways. There needs to be a page that can be shown to people to sort of be the "truth" to how to do things.

Things to include (but not limited to):
- [ ] Code blocks _must_ technically compile
- [ ] Try to leave comments out of code blocks and put in comment blocks instead
- [ ] Try to have code blocks match other code blocks as much as possible
- [ ] If there's more than one way to do things, you can write both in a code block, but differentiate them with a comment
- [ ] Anything that's not intuitive to a beginner needs a comment
- [ ] Operators need to show order (prefix, postfix, infix)
- [ ] You should have `code`, or `code` + `comment`, or `not-implemented`, or `not-implemented` + `comment`
- [ ] ...

**Comment by ClJarvis** [comment]
I would like to work on this. I like writing documentation.

**Comment by geekygirlsarah** [comment]
Yeah! I can assign it to you. And if nothing else you can start the page and I can always add to it as I think of other best practices.

Let me know if you have any questions!

**Comment by ClJarvis** [comment]
Thank you,  I'm sure as I build I'll have some questions.

**Comment by geekygirlsarah** [comment]
I'm working on pull request #26 which will change up the structure of the docs and break down some pages to be a bit more easy to read. It'll break your local version, but you can copy/paste whatever you write for this into the "best practices" page when I get it up. Is that ok?

**Comment by ClJarvis** [comment]
That should work. I'm adding content not code so It'll be easy to paste.

**Comment by ClJarvis** [comment]
I have pushed some Best Practices to a Best Practices branch on my fork. Is there an example code block that should be on the page?

**Comment by geekygirlsarah** [comment]
> I have pushed some Best Practices to a Best Practices branch on my fork. 

Sweet!

> Is there an example code block that should be on the page?

No, the template generator should generate what they need for it. Unless you think there should be something with how you've written it?

**Comment by ClJarvis** [comment]
Oh, The Template Generator takes care of it. Then no, it probably doesn't need an example.

**Comment by ClJarvis** [comment]
Can you look at the content I have so far for the Best Practices?

What else should be added?

**Comment by geekygirlsarah** [comment]
Assuming that [this](https://github.com/codethesaurus/docs/compare/main...ClJarvis:docs:Best_Practices) is what you added, it looks good so far. I can always add some things on as I think of them. I appreciate you adding this!

**Comment by geekygirlsarah** [comment]
Maybe one thing you could add at the top is mention that CT is a reference tool for what exists in a language to compare to other languages. If it doesn't exist, you shouldn't add it (so don't write an algorithm to do equivalent functionality). Also it's not designed to teach beginners how to program, but should still be written so beginners can understand the parts of the language that exist. 

(Feel free to phrase those how you want.)

**Comment by geekygirlsarah** [comment]
Closed as #37 did this.
