### ISSUE TITLE
Update install docs to use Docker Compose

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/docs#15]
The install directions for Code Thesaurus still show how to spin up the Docker container manually. A Docker Compose file was added to make this a lot easier, but the instructions weren't ever updated to reflect this.

1. In the install directions, add a section above the other two (Docker Container and Manual Install) for Docker Compose
2. Add instructions on how to run it. (It should be, I believe, just `docker-compose up`)
3. Verify and test the instructions work for you

If you can test it in one operating system, it should work for the others. (i.e. if you test in Windows, it should work the same in Mac.)

**Comment by geekygirlsarah** [comment]
And let me know if you have any questions or need any help!

**Comment by marce1994** [comment]
@geekygirlsarah With
```docker-compose up``` isn't working.
I have deleted ```target: cthesaurus-img``` from ```docker-compose.yml``` to make it run.
Then I changed the ```CMD python manage.py runserver 0:8000``` to ```CMD python manage.py runserver 0.0.0.0:8000``` to make it work finally.

![image](https://user-images.githubusercontent.com/358126/138006739-4fb5861d-25bf-4dec-a7a5-987e5e50d1f1.png)
But I don't know if that's fine :/

**Comment by geekygirlsarah** [comment]
That works! And yeah, I was finding the same when I was trying to run it, so that's fine!

**Comment by geekygirlsarah** [comment]
Feel free to make a pull request with it!
