### ISSUE TITLE
Add a "Quick Start" or "Getting Started" page

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/docs#25]
There's a lot of deep-dive pages, but so few people read those. The project also tends to attract some newer to development people (which I love!) but it means they need a bit more hand-holding than I have the capability to give.

I'm wondering if we need a page that's a super quick "how to get started" kidn of page that, if someone doesn't want to read all the pages related to what they're doing, can at least follow the like 8 steps to get going on this page. This could replace the steps I keep putting in CT's issues with several steps in it.

I don't want this to replace other pages, more like supplement them. Like when you buy a new device/appliance and it comes with the 40 page manual but also a quick one page sheet to get you going faster. That, but for Code Thesaurus.

**Comment by BinniesLite** [comment]
Hi @geekygirlsarah, I love the concept of your site, I can help you with writing the "quick start" documentation. Do you want it to be about helping the contributors setting up the project, know where to find stuff for the projects or how to use codeThesaurus?

**Comment by geekygirlsarah** [comment]
> Hi @geekygirlsarah, I love the concept of your site,

Thank you!

> I can help you with writing the "quick start" documentation. Do you want it to be about helping the contributors setting up the project, know where to find stuff for the projects or how to use codeThesaurus?

I think mostly the former. How to set up the project quickly. Maybe something along the lines of:
> 1. Install Docker.  (read more at [Docs URL])
> 2. Run `docker-compose up`.  (read more at [Docs URL])
> 3. Edit the thesaurus files.   (read more at [Docs URL])

Where the steps are easy and can get someone up and going quickly, but if they wanted to read more, they could jump to the more in-depth page.

And I'm happy to leave it up to you how you want to write that out!

Want me to assign it to you?

**Comment by BinniesLite** [comment]
Sure, I'll be happy to help!

**Comment by geekygirlsarah** [comment]
Sweet, thanks!

Let me know if you have any questions.

**Comment by geekygirlsarah** [comment]
I'm working on pull request #26 which will change up the structure of the docs and break down some pages to be a bit more easy to read. It'll break your local version, but you can copy/paste whatever you write for this into the "getting started"/"quick start" page when I get it up. Is that ok?

**Comment by BinniesLite** [comment]
That's fine, I will re-write the doc accordingly. I'll update you with a draft when finished

**Comment by geekygirlsarah** [comment]
Thanks!

**Comment by geekygirlsarah** [comment]
Closed as it was done in #27 and updated in #33
