### ISSUE TITLE
Fill in FAQ from old responses 

### ISSUE THREAD

**Issue by monkeywithacupcake** [codethesaurus/docs#29]
There is a lot of detail in responses to Issues and comments in PRs. These could be used to fill in the empty FAQ. 

Can I be assigned this task to get it started?

For example, from [issue #225](https://github.com/codethesaurus/codethesaur.us/issues/225)

> _**What does "Not implemented in this language" mean exactly?**_
> This means that this feature is a thing you can look up on Code Thesaurus, but doesn't necessarily mean the language can do it. So not all languages can do all things other languages can, so this is a way of marking in the file "we're looked at this in the file, and this language can't do it."

**Comment by geekygirlsarah** [comment]
Yeah! (I actually forgot there was a FAQ, if I'm honest, lol.) If you can find commonly asked questions, or even questions you have as you look over things, add them in! I could even offer answers if you don't have them.

**Comment by monkeywithacupcake** [comment]
There are also some questions sprinkled in other pages that maybe should go into FAQ, like **Why JSON?** in the Project Architecture page. 
I am not sure if it makes most sense to duplicate them or to point to the place where it is answered. 
Right now, I'm pointing.

**Comment by geekygirlsarah** [comment]
Or could be like short summary and "read more in the [whatever page]" too.

**Comment by monkeywithacupcake** [comment]
I'm reading through the [minor version Issue discussion](https://github.com/codethesaurus/codethesaur.us/pull/467) - and this seems like it is probably a FAQ that is mostly silent - so, the examples from rust and python are not ones that I found in the code - like, I don't see where the "since 1.59" shows up for rust string formatting. And, when I look in the python code, some pages have meta version "3" and others have "3.10" but I don't see anything saying "since 3.x".  

Can you clarify what is desired with regard to minor version handling? The docs only address major version as far as I can tell.

**Comment by geekygirlsarah** [comment]
Good question. I think presently we can have any number of major versions (like Python 1, 2, 3) but only the latest minor version (so Python 3.10 not 3.9 or 3.8).  If something new is added, for now they can leave a comment (i.e. `"comment": "Added in version 3.7"`). Maybe there should be a field for when it was added but that's an issue for the future.

As for Rust... there's only version 1.x and they keep adding features to it. But it'd be really complex to keep adding minor versions to CT, notably for maintainability. So I think they keep adding onto version 1 but can add when new features are added.
