### ISSUE TITLE
The Quick Start Guide gives a 404

### ISSUE THREAD

**Issue by monkeywithacupcake** [codethesaurus/docs#30]
The path to quick start has the `.md` attached, so it doesn't show up even though there is data. 

Looks like `https://docs.codethesaur.us/quick_start.md` and pretty sure it should look like `https://docs.codethesaur.us/quick_start/`

But also, that change alone does not fix the problem - perhaps the updated file was merged in as markdown but the website was not compiled afterwards?

**Comment by geekygirlsarah** [comment]
Good catch! I fixed it with 04e3a88570b38530d7954c5c04b0aba86a6bb872
