### ISSUE TITLE
Docs for Add a New Language are incomplete

### ISSUE THREAD

**Issue by monkeywithacupcake** [codethesaurus/docs#32]
When someone adds a new language, they also need to add a folder for the version. And, if they are adding files for structures, they will not be able to get the templates from the URL as given because the language will not exist in the live site - so they need to use their local version. 

Fix should be simple. Something like:

In **Add on a New Language** after " From there, assign it to a directory name in the JSON structure." Add the directory and a subdirectory for the latest version (or the version you are providing)

In **Add an Existing Structure Set to a Language** Say, if you are adding a new language, get the structure templates from: "localhost:8000/reference/?concept=<your_concept>&lang=<language>%3B<language_major_version>" or something like that.

**Comment by geekygirlsarah** [comment]
Also they can run the generate_template command. It's `python manage.py generate_templates --language_version=<language_version> <language> <structure>`
