### ISSUE TITLE
Fix formatting errors after importing docs from GitHub wiki/Markdown files

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/docs#4]
I moved many of the .md files over to this docs repo for docs.codethesaur.us. Some of the formatting didn't transfer over right.

Go through each of the .md files in this repo and just make sure the expected formatting actually turns out right on the actual site.

**Comment by Swastik2000** [comment]
I can work on this issue.

**Comment by geekygirlsarah** [comment]
Yeah, I'll give this to you too. Let me know if there's any questions. Thank you!

**Comment by Swastik2000** [comment]
@geekygirlsarah  I have filtered out the formatting issues. Right now I want to host on Netflix so as to see that the changes are visible or not. Can you please guide me on how to Host Mkdocs in Netlify.

**Comment by geekygirlsarah** [comment]
You can run it locally. That's probably the fastest way to do it. It's Python-based. Instructions are [here](https://www.mkdocs.org/getting-started/).

There's also trying to run it in Docker (I see lots of attempts at it [here](https://hub.docker.com/search?q=mkdocs&type=image)). I could maybe try to make a Docker image for it too.

**Comment by geekygirlsarah** [comment]
Oh, deploy previews are up for this project too. If you make a PR, you can go to https://deploy-preview-#--code-thesaurus-docs.netlify.app   (replace # with whatever PR number it is), you can take a look at it. It may take 15-30 seconds after making the PR for the preview to work.

**Comment by Swastik2000** [comment]
#10 
@geekygirlsarah I have completed the above-mentioned task.
