### ISSUE TITLE
Thesaurus docs should reflect changes to allow for code comments and names no longer in file

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/docs#7]
The `name` field within a concept is pulled from the meta language files now and is not used in thesaurus language files anymore. This can be removed from the documentation.

Also the `comment` field has been added to allow for someone to describe parts of the code and explain what the different variable names or keywords refer to in the code.

Both of these should be edited in the Thesaurus Files page but anywhere else there might reference to them.

**Comment by cafce25** [comment]
I'll be working on this in parallel to codethesaurus/codethesaur.us#208 since the both are closely related.

**Comment by cafce25** [comment]
I think this is resolved by #20, I just forgot to link it.

**Comment by geekygirlsarah** [comment]
You're right. I can close this!
